import { StudioService } from '../types';

export const INITIAL_STUDIO_SERVICES: StudioService[] = [
  {
    id: 'passport_photo',
    code: 'PASSPORT',
    title: 'Passport Photo',
    titleBn: 'পাসপোর্ট ছবি প্রিন্ট (৪ বা ৮ কপি শিট)',
    descriptionBn: 'স্টুডিও কোয়ালিটি ল্যাব পাসপোর্ট ছবি ও ভেরিফিকেশন',
    icon: '📸',
    category: 'photo',
    basePriceBDT: 50,
    enabled: true,
    autoApprove: false,
    preferredPrinterId: 'printer_epson_l805',
    preferences: {
      paperType: 'glossy',
      quality: 'high',
      color: 'color',
      paperSize: 'Passport Grid (4-in-1)',
      dpi: 2880,
      defaultCopies: 1,
      borderless: true,
    },
  },
  {
    id: 'stamp_photo',
    code: 'STAMP',
    title: 'Stamp Photo',
    titleBn: 'স্ট্যাম্প সাইজ ছবি প্রিন্ট',
    descriptionBn: 'অফিসিয়াল স্ট্যাম্প ও আবেদনপত্রের ছবি',
    icon: '🪪',
    category: 'photo',
    basePriceBDT: 30,
    enabled: true,
    autoApprove: false,
    preferredPrinterId: 'printer_epson_l805',
    preferences: {
      paperType: 'glossy',
      quality: 'high',
      color: 'color',
      paperSize: 'Stamp Size',
      dpi: 2880,
      defaultCopies: 1,
      borderless: true,
    },
  },
  {
    id: 'nid_card',
    code: 'NID',
    title: 'NID / Smart Card Copy',
    titleBn: 'এনআইডি / স্মার্ট কার্ড কপি',
    descriptionBn: 'জাতীয় পরিচয়পত্র ও স্মার্ট কার্ডের কপি',
    icon: '💳',
    category: 'card',
    basePriceBDT: 40,
    enabled: true,
    autoApprove: false,
    preferredPrinterId: 'printer_hp_laserjet',
    preferences: {
      paperType: 'laminated',
      quality: 'normal',
      color: 'bw',
      paperSize: 'A4 (8.27x11.69 in)',
      dpi: 1200,
      defaultCopies: 1,
      borderless: false,
    },
  },
  {
    id: 'photo_4r',
    code: 'PHOTO4R',
    title: '4R Photo Print',
    titleBn: '৪-আর ল্যাব ফটো প্রিন্ট',
    descriptionBn: 'হাই-গ্লসি ফটো পেপারে পারিবারিক ও অ্যালবাম প্রিন্ট',
    icon: '🖼️',
    category: 'photo',
    basePriceBDT: 35,
    enabled: true,
    autoApprove: false,
    preferredPrinterId: 'printer_epson_l805',
    preferences: {
      paperType: 'glossy',
      quality: 'high',
      color: 'color',
      paperSize: '4R (4x6 in)',
      dpi: 2880,
      defaultCopies: 1,
      borderless: true,
    },
  },
  {
    id: 'doc_a4',
    code: 'A4DOC',
    title: 'A4 Document',
    titleBn: 'A4 ডকুমেন্ট ও অনলাইন আবেদনপত্র',
    descriptionBn: 'পরীক্ষার প্রবেশপত্র, চালান, ফরম ও সাধারণ PDF ফাইল',
    icon: '📄',
    category: 'document',
    basePriceBDT: 5,
    enabled: true,
    autoApprove: true,
    preferredPrinterId: 'printer_hp_laserjet',
    preferences: {
      paperType: 'plain',
      quality: 'normal',
      color: 'bw',
      paperSize: 'A4 (8.27x11.69 in)',
      dpi: 600,
      defaultCopies: 1,
      borderless: false,
    },
  },
];
